version: 2.1
jobs:
  build:
    environment:
      - JAVA_OPTS: "-XX:ReservedCodeCacheSize=256M -Xms1g -Xmx3g -Xss2m"
      - AWS_REGION: "ap-northeast-1"
      - TEST_TIME_FACTOR: "5"
    machine: true
    steps:
      - run:
          command: |
            sudo apt-get update -qq && sudo apt-get install -y libaio1 libevent-dev
            sudo apt-get install -y software-properties-common
            sudo add-apt-repository ppa:rpardini/adoptopenjdk -y
            sudo apt-get update -qq
            sudo apt install adoptopenjdk-8-installer -y
            sudo apt-get install -y maven git
            echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list
            sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823
            sudo apt-get update -qq
            sudo apt-get install sbt
      - checkout
      - restore_cache:
          key: scala-library-dependencies-{{ checksum "build.sbt" }}
      - run:
          command: sbt scalafmtCheck
      - run:
          command: sbt +test
      - save_cache:
          paths: [ "~/.sbt/boot", "~/.ivy2/cache", "~/.cache/coursier" ]
          key: scala-library-dependencies-{{ checksum "build.sbt" }}
  release:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - restore_cache:
          key: scala-library-dependencies-{{ checksum "build.sbt" }}
      - run:
          command: git fetch --tags
      - run:
          command: sbt ci-release
workflows:
  version: 2
  build-and-release:
    jobs:
      - build:
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
      - release:
          requires:
            - build
          filters:
            branches:
              only: main
            tags:
              only: /^v\d+\.\d+\.\d+$/

